import { createHash } from 'crypto';
import { config } from './config';

/**
 * Deterministic JSON encoding (sorted object keys). Required so every
 * validator hashes identical bytes for the same logical content.
 *
 * TODO: replace with a real canonical encoding (RLP / CBOR / Protobuf).
 */
export function deterministicStringify(value: unknown): string {
  if (value === null || value === undefined) return JSON.stringify(value ?? null);
  if (typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) {
    return '[' + value.map(deterministicStringify).join(',') + ']';
  }
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return (
    '{' +
    keys
      .map((k) => JSON.stringify(k) + ':' + deterministicStringify(obj[k]))
      .join(',') +
    '}'
  );
}

export function sha256(s: string): string {
  return createHash('sha256').update(s).digest('hex');
}

export function hashTransaction(tx: Record<string, unknown>): string {
  const { transactionHash, ...rest } = tx;
  return sha256(deterministicStringify(rest));
}

export function hashBlock(block: {
  blockNumber: number;
  previousHash: string;
  timestamp: string;
  transactions: unknown[];
  validatorSignatures: unknown[];
}): string {
  return sha256(
    deterministicStringify({
      blockNumber: block.blockNumber,
      previousHash: block.previousHash,
      timestamp: block.timestamp,
      transactions: block.transactions,
      validatorSignatures: block.validatorSignatures,
    }),
  );
}

/**
 * Mock validator signature.
 *
 * TODO: replace with real Ed25519 / BLS12-381 signatures backed by an HSM
 * for the institution that operates this validator.
 */
export function mockSign(content: string): string {
  return sha256(`${config.validatorId}::${config.privateKey}::${content}`);
}

/**
 * Mock partial decryption share.
 *
 * In a real threshold scheme, each validator holds a key share generated by
 * Distributed Key Generation (DKG) and produces a partial decryption of the
 * encrypted aggregate. Combining ≥ threshold shares yields the cleartext.
 *
 * TODO: replace with Pedersen-DKG or Feldman-VSS based threshold ElGamal /
 * Paillier decryption.
 */
export function mockDecryptionShare(electionId: string, encryptedAggregate: string): string {
  const inner = sha256(
    `${config.validatorId}::${config.privateKey}::${electionId}::${encryptedAggregate}`,
  );
  return `mock-share:${config.validatorId}:${inner}`;
}
